using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;

public class GiveRewardOnClear : MonoBehaviour
{
    public PlayerState playerState;

    [Header("Clear reward settings")]
    [SerializeField] private int clearGold;
    [SerializeField] private TextMeshProUGUI rewardText;
    [SerializeField] private GameObject slotParent;
    [SerializeField] private GameObject itemSlot;
    


    private void OnEnable()
    {
        clearGold = (int)(clearGold * (1.0f + playerState.Player_More_Economy));


        // UI ê°±ì‹ 
        rewardText.text = "ë³´ìƒ: " + clearGold + "G";

        // ìŠ¬ë¡¯ ìƒì„±
        GameObject goldPot = Instantiate(itemSlot, slotParent.transform, false);
        SlotInven goldPotData = goldPot.GetComponent<SlotInven>();
        goldPotData.setInit(new ItemData(ItemDatabase.Instance.FetchItemById(ItemDatabase.ID_GOLD_POT), clearGold));

        int currentStage = PlayerStatusInMain.Instance.GetCurStage(); // â† í˜„ì¬ ìŠ¤í…Œì´ì§€ index ë°›ì•„ì™€ì•¼ í•¨

        PlayerStatusInMain.Instance.CompleteStage(currentStage, clearGold, success =>
        {
            if (!success)
            {
                Debug.LogError("âŒ ìŠ¤í…Œì´ì§€ í´ë¦¬ì–´ ì €ì¥ ì‹¤íŒ¨");
                return;
            }
            Debug.Log("ğŸ‰ ìŠ¤í…Œì´ì§€ í´ë¦¬ì–´ ë³´ìƒ ì§€ê¸‰ ì™„ë£Œ!");
        });
    }
}
